//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.10716.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{


    public partial class DateTime_EditField
    {

        protected System.Web.UI.WebControls.TextBox TextBox1;

        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;

        protected System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator1;

        protected System.Web.DynamicData.DynamicValidator DynamicValidator1;
    }
}
