//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace APRESS.SP2010.SolutionValidatorDemo.Layouts.SolutionValidatorDemo {
    
    
    public partial class SolutionValidationErrorPage {
    }
}
